version: "3"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: "theswisssystem-mysql"
    environment:
      MYSQL_DATABASE: "theswisssystem"
      MYSQL_USER: "theswisssystem"
      MYSQL_PASSWORD: "theswisssystem"
      MYSQL_ROOT_PASSWORD: "theswisssystemroot"
    ports:
      - "3306:3306"