spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/theswisssystem"
    username: "theswisssystem"
    password: "theswisssystem"
    driverClassName: "com.mysql.cj.jdbc.Driver"
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect